feat(notifications): Update Subscription DTO to adopt common Address
edgexfoundry/go-mod-core-contracts pull request #549
Opened 2021-03-16 10:54 UTC by FelixTing

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number: #545 

## What is the new behavior?
Subscription Channel is of type Address.

Close #545 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

2021-03-16 16:02 UTC, lenny-intel requested changes

2021-03-17 04:14 UTC, FelixTing commented on v2/dtos/address.go
> +	channelModels := make([]models.Address, len(channelDTOs))
It's a copy-paste mistake. Modified. https://github.com/edgexfoundry/go-mod-core-contracts/pull/549/commits/99ccf6c49d8fc97adb30c6b7f071d5d7ee0b257c

2021-03-17 04:14 UTC, FelixTing commented on v2/dtos/requests/subscription.go
> +		err = c.Validate()
Good catch. Thanks! Channel type check has been added. https://github.com/edgexfoundry/go-mod-core-contracts/pull/549/commits/3e070a1aec28e0ba79568e9611d0a94497b699a7

2021-03-17 21:34 UTC, lenny-intel approved these changes
LGTM

2021-03-17 21:34 UTC, merged