feat: add CBOR support in EventClient for binary reading
edgexfoundry/go-mod-core-contracts pull request #550
Opened 2021-03-17 08:20 UTC by hahattan

Signed-off-by: Chris Hung <chris@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number: fix #543 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-03-17 11:53 UTC, cloudxxx8 requested changes

2021-03-17 11:53 UTC, cloudxxx8 commented on v2/clients/http/utils/common.go
> +func createRequestWithRawData(ctx context.Context, httpMethod string, url string, data interface{}, cborEncoding bool) (*http.Request, errors.EdgeX) {
don't use bool because we might have other encoding in the future.
please use string and leverage clients.ContentTypeCBOR / clients.ContentTypeJSON.

2021-03-17 21:29 UTC, lenny-intel reviewed
LGTM, once addressed @cloudxxx8 comment.

2021-03-18 03:49 UTC, cloudxxx8 requested changes

2021-03-18 03:49 UTC, cloudxxx8 commented on v2/clients/http/device.go
> +	err = utils.PostRequest(ctx, &res, dc.baseUrl+v2.ApiDeviceRoute, reqs, "")
although the default value = JSNO is a good option, please still put clients.ContentTypeJSON to all the PostRequest call

2021-03-18 03:49 UTC, cloudxxx8 commented on v2/clients/http/event.go
> +	if v := os.Getenv("EDGEX_ENCODE_ALL_EVENTS_CBOR"); v == "true" {
define constant for "EDGEX_ENCODE_ALL_EVENTS_CBOR" and "true"

2021-03-18 08:09 UTC, cloudxxx8 approved these changes
LGTM

2021-03-18 08:35 UTC, merged