feat(notifications): Create Transmission DTO and Model
edgexfoundry/go-mod-core-contracts pull request #580
Opened 2021-04-14 13:42 UTC by FelixTing

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number: #514 

## What is the new behavior?
Create Transmission DTO and Model for support-notifications V2 API

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

2021-04-14 15:55 UTC, lenny-intel approved these changes
LGTM

2021-04-14 16:09 UTC, cloudxxx8 requested changes
Replace `TRXESCALATED` with just `ESCALATED`

2021-04-15 01:57 UTC, FelixTing commented
Replaced `TRXESCALATED` with `ESCALATED`

2021-04-15 05:38 UTC, cloudxxx8 requested changes

2021-04-15 05:38 UTC, cloudxxx8 commented on v2/models/transmissionstatus.go
> +	Trxescalated = "ESCALATED"
modify the const name

2021-04-15 10:33 UTC, cloudxxx8 approved these changes
LGTM

2021-04-15 10:33 UTC, merged