feat: implement v2 SystemManagementClient
edgexfoundry/go-mod-core-contracts pull request #625
Opened 2021-05-27 04:17 UTC by hahattan

Signed-off-by: Chris Hung <chris@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number: fix #622 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-05-27 05:36 UTC, cloudxxx8 approved these changes
LGTM

2021-05-28 18:17 UTC, lenny-intel requested changes

2021-05-28 18:17 UTC, lenny-intel commented on v2/clients/http/system.go
> +	urlPath := path.Join(v2.ApiBase, "health", strings.Join(services, v2.CommaSeparator))
These need to change to using query parameter for services list per Core WG discussion on 5/27/21

2021-06-02 07:55 UTC, hahattan commented
change in this PR is now aligned with https://github.com/edgexfoundry/edgex-go/pull/3527

2021-06-02 17:01 UTC, lenny-intel approved these changes
LGTM

2021-06-02 17:01 UTC, merged