feat!: update data type in ResourceProperties
edgexfoundry/go-mod-core-contracts pull request #809
Opened 2023-02-22 06:50 UTC by hahattan

BREAKING CHANGE: update mask,shift,base,scale,offset to numeric data type

also rename 'Others' to 'Optional' for the consistency with message broker settings.

closes #770

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2023-02-22 20:15 UTC, lenny-intel requested changes

2023-02-22 20:15 UTC, lenny-intel commented on dtos/deviceprofile_test.go
> +			Optional:  testTags,
Why using `testTags`? Optional is not for tags, so please use something more relevant to what we expect it to be used for.

2023-02-23 04:50 UTC, lenny-intel approved these changes
LGTM

2023-02-25 18:32 UTC, iain-anderson requested changes
Can we use json.Number for scale, offset and base - so that they can be integer or float?

2023-03-01 03:17 UTC, hahattan commented
> Can we use json.Number for scale, offset and base - so that they can be integer or float?

`json.Number` is alias of `string` which provides useful methods to transform value to numeric data type.
But there still will be error in the same place if user provides illegal value:
https://github.com/edgexfoundry/device-sdk-go/blob/b46b419fd49731d0deb4deed8e6127ef6a42900c/internal/transformer/transformresult.go#L92-L93

Using `float64` directly can avoid the error during device profile creation but it's a breaking change.

Another way to improve this is to use `json.Number` for  these properties, but leverage validator to check the type.
For example https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Numeric for `base`, `scale` and `offset`.
But we might need to implement custom tag for `mask` and `shift`

@lenny-intel @cloudxxx8 @iain-anderson thought ?

2023-03-08 00:17 UTC, cloudxxx8 commented
@iain-anderson is it ok?

2023-03-08 14:00 UTC, iain-anderson commented
OK with this as is

2023-03-09 04:59 UTC, merged