feat: Add the http clients/dtos of KVS and registry for Keeper
edgexfoundry/go-mod-core-contracts pull request #879
Opened 2024-02-22 05:24 UTC by jackchenjc

closes #873 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2024-02-27 09:06 UTC, cloudxxx8 commented
@jackchenjc may we move those clients to config and registry module respectively?

2024-03-05 07:15 UTC, cloudxxx8 commented
@lenny-intel we can dicuss in the tomorrow's meeting.
Since keeper is in the momo repo edgex-go, its dtos and models should be located in the go-mod-core-contracts.
The client lib is defined here for other go services.  There is no direct dependency from go-mod-registry and go-mod-configuration right now.

2024-03-06 09:16 UTC, cloudxxx8 commented
@lenny-intel according to the Core WG meeting discussion today, this PR can be reviewed and merged first

2024-03-06 21:36 UTC, lenny-intel requested changes

2024-03-07 08:39 UTC, jackchenjc commented on clients/http/kvs.go
> +func NewKVSClient(baseUrl string, authInjector interfaces.AuthenticationInjector) interfaces.KVSClient {
Hi Lenny,

You're right, this client should be used in go-mod-configuration and we will encounter the issue you mentioned.

Would you please give us more hints about your suggestion, like what exactly should be added to the struct,  thanks.

2024-03-11 07:02 UTC, jackchenjc commented on dtos/requests/registration.go
> +}
They should have already been implemented [here](https://github.com/edgexfoundry/go-mod-core-contracts/pull/879/files#diff-424d0d6b55f61c7c1a8a6a6c6fc5d77d992b78f2e0bf995db6b4e08cd766cc48R32-R59).

2024-03-12 02:21 UTC, jackchenjc commented on dtos/requests/registration.go
> +}
The conversion functions to and from model are currently declared in [dto/registration.go](https://github.com/edgexfoundry/go-mod-core-contracts/pull/879/files#diff-424d0d6b55f61c7c1a8a6a6c6fc5d77d992b78f2e0bf995db6b4e08cd766cc48R32-R59), which is consistent with existing DTOs, would you suggest to move them to `dtos/requests/registration.go`?

2024-03-12 02:24 UTC, jackchenjc commented on clients/http/kvs.go
> +func NewKVSClient(baseUrl string, authInjector interfaces.AuthenticationInjector) interfaces.KVSClient {
Hi @lenny-intel,
When you have a moment, could you please review this conversation, thanks.

2024-03-14 06:52 UTC, jackchenjc commented on clients/interfaces/kvs.go
> +// KVSClient defines the interface for interactions with the kvs endpoint on the Edge Xpert core-keeper service.
Done.

2024-03-14 06:52 UTC, jackchenjc commented on clients/interfaces/registry.go
> +// RegistryClient defines the interface for interactions with the registry endpoint on the Edge Xpert core-keeper service.
Done.

2024-03-14 06:53 UTC, jackchenjc commented on common/constants.go
> -	RegexCommand = "ds-regexcmd"    //query string to specify if the command name is in regular expression format
It was removed accidentally, already reverted.

2024-03-14 06:53 UTC, jackchenjc commented on dtos/registration.go
> +func (r *Registration) Validate() error {
Done.

2024-03-14 06:54 UTC, jackchenjc commented on dtos/registration.go
> +	LastConnected int64       `json:"lastConnected"`
Done.

2024-03-14 06:54 UTC, jackchenjc commented on dtos/registration.go
> +	Type     string `json:"type"`
Done.

2024-03-14 06:54 UTC, jackchenjc commented on dtos/requests/registration_test.go
> +		{"invalid AddRegistrationRequest, invalid HealthCheck interval", invalidInterval, true},
Done.

2024-03-14 16:05 UTC, lenny-intel commented on clients/http/kvs.go
> +func NewKVSClient(baseUrl string, authInjector interfaces.AuthenticationInjector) interfaces.KVSClient {
HI @jackchenjc, the `authInjector` can be simply added to the

2024-03-14 16:23 UTC, lenny-intel commented on dtos/requests/registration.go
> +}
Your correct here. Sorry, I was confused on which file this is... ;-(

2024-03-14 16:26 UTC, lenny-intel approved these changes
LGTM, remaining comments apply to other modules when using these additions.

2024-03-18 03:07 UTC, cloudxxx8 approved these changes
LGTM

2024-03-18 03:08 UTC, merged